import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./_base.scss";

const inter_tight = Inter_Tight({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter_tight.className}>{children}</body>
    </html>
  );
}
